.idea/.gitignore, .idea/backend.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, momentum-dao-be/build.gradle, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/WorkCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/request/WorkStartRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkCreateResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkStartResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkSummaryDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkTimeService.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/validator/IpValidator.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/validator/WorkCreateValidator.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Work.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkType.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkTypeName.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkTypeRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/exception/WorkException.java, momentum-dao-be/src/test/java/com/dao/momentum/work/command/application/controller/WorkCommandControllerTest.java
closes null
(퇴근 등록까지 구현해야 이슈 완료)
---
📌 개요
- 출근 등록 기능 구현
🔨 주요 변경 사항
- 출근 등록 기능 구현 (검증 로직 포함)
- 검증 로직이 길어서 유지보수를 위해 Validator 등 클래스로 분리
- String으로 관리하던 `WorkTypeName`을 Enum으로 수정
- GlobalExceptionHandler에 `WorkException`에 대한 핸들링 추가 
- 테스트 코드 작성
✅ 리뷰 요청 사항
⭐ 관련 이슈
#13
---
일단 기본적인 출근 등록은 잘 구현된 것으로 보이고, 복잡한 경우는 초기 데이터 생기고 Postman으로 제대로 해봐야할 듯합니다.
로직이 지금도 꽤 복잡해서, 일단 주 52시간 이상 근무 불가 로직은 따로 이슈 파고 추후에 가능하면 구현할까 생각 중입니다.
(성능적인 부분도 우려됨)
=> feat: 출근 등록 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/ApproveController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ApproveMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveServiceImpl.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/ApproveControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveServiceImplTest.java
closes #6
---
📌 개요
사원이 받은 결재 문서 조회 기능 구현
🔨 주요 변경 사항
- 컨트롤러 만들기
-  `ApproveController` : /approval/documents/received 로 endpoint 설정 
- 컨트롤러 테스트 생성
- 서비스 만들기
- `ApproveService`, `ApproceServiceImpl` 만들기 
- 결재 문서 조회 메서드 생성  
- 서비스 테스트 생성 
- mapper 만들기  
- 받은 문서 조회 메서드 생성 
- 받은 문서 개수 구하는 메서드 생성
- 존재하는 사원인지 확인하는 메서드 생성    
✅ 리뷰 요청 사항
⭐ 관련 이슈
#6
=> feat : 받은 문서 조회 기능 구현

.idea/misc.xml, .idea/workspace.xml, momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/PositionCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/request/PositionUpdateRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/response/PositionUpdateResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/service/PositionCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/aggregate/Position.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/PositionRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/infrastructure/repository/JpaPositionRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/exception/PositionException.java, momentum-dao-be/src/test/java/com/dao/momentum/organization/position/command/application/service/PositionCommandServiceTest.java
closes #102 
---
📌 개요
- 직위 변경 시 직위명, 직위 단계, 직위 원본 존재여부를 확인 한 후 직위를 변경한다.
- 해당 직위 단계 변경시 다른 직위의 단계를 조정한다.
- 마스터 관리자만 직위를 수정할 수 있다.
🔨 주요 변경 사항
- PositionCommandController 및 PositionCommandService 메소드 구현
- 직위 변경 테스트코드 작성
- securityConfig 마스터 관리자 엔트포인트 추가
✅ 리뷰 요청 사항
- 직위 수정 기능 로직 확인
- 테스트코드 로직 확인
⭐ 관련 이슈
#102
=> feat: 직위 수정 기능 구현

momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/AdminApproveControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/ApproveControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/AdminApproveServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveServiceImplTest.java
closes #3 , #6 
---
📌 개요
결재 내역 조회 컨트롤러, 서비스 테스트 코드 수정
🔨 주요 변경 사항
- 잘못된 더미 데이터 수정하기
- 컨틀롤러 테스트에서 모의 객체에게 매개변수를 넘길 때, `Mockito.any()`로 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#3 , #6
=> [test #3, #6] 결재 내역 조회 컨트롤러, 서비스 테스트 코드 수정

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/AdminApproveQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ReceivedApproveMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/approve/ReceivedApproveMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/AdminApproveQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/AdminApproveQueryServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImplTest.java
closes #3
---
📌 개요
Command와 Query를 구분하기 위해 클래스명 변경
🔨 주요 변경 사항
- `AdminApproveController, AdminApproceService` 중간에 Query 단어 추가
- `ApproveMapper` -> `ReceviedApproveMapper`로 변경
✅ 리뷰 요청 사항
⭐ 관련 이슈
#3
=> refactor : 클래스명 변경 (Query 추가)

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveType.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/NotFoundApproveException.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/ApproveQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveFileDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveLineDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveLineGroupDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveLineListDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveRefDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveCancelDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveProposalDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveReceiptDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/BusinessTripDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/OvertimeDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/RemoteWorkDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/VacationDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/WorkCorrectionDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/request/ApproveListRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/response/ApproveDetailResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ApproveDetailMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/AdminApproveQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/ApproveQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/AdminApproveQueryServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImplTest.java
closes #8 
---
📌 개요
결재 문서 상세 조회 기능 구현
🔨 주요 변경 사항
- ApproveQueryController
- /approval/documents/{documents}로 endpoint 설정
- ApproveQueryService, ApproveQueryServiceImpl
- 결재 문서 상세 조회 메서드 생성 `getApproveDetail`
- 결재 문서 상세 조회 시 일반 결재와 취소 결재를 나눠서 return하기 때문에 각각 메서드 생성, 결재 상세 내역을 빌드 해주는 메서드 생성 `getCancelApproveDetail`, `getNormalApproveDetail`, `buildApproveDetailResponse`
- 결재 문서의 종류에 따라서 다른 폼 내용을 전달해주기 위해 `resolveFormDetail` 메서드 생성
- 요청 시 응답과 에러 처리 완료
- 서비스 테스트
- ApproveDetailMapper
- 결재 내역 조회 메서드
- 결재 첨부 파일 조회 메서드
- 결재선과 결재선에 있는 사원 목록을 조회하는 메서드
- 참조자를 조회하는 메서드
- 결재 문서 종류 별로 상세 조회하는 메서드 생성
- 요청, 응답 객체
- 각각의 종류 별로 DTO를 생성함 (결재, 결재선, 결재선 목록, 결재 문서)
- `ApproveDetailResponse` 생성
✅ 리뷰 요청 사항
로직 점검 
⭐ 관련 이슈
#8
=> feat : 결재 문서 상세 조회 기능

momentum-dao-be/build.gradle, momentum-dao-be/docker-compose.yml, momentum-dao-be/src/main/java/com/dao/momentum/common/config/KafkaConfig.java, momentum-dao-be/src/main/java/com/dao/momentum/common/kafka/dto/NotificationMessage.java, momentum-dao-be/src/main/java/com/dao/momentum/common/kafka/producer/NotificationKafkaProducer.java, momentum-dao-be/src/main/resources/application.yml
closes #180 
---
📌 개요
Kafka 기반 알림 발송 템플릿 구현
🔨 주요 변경 사항
- Kafka 관련 의존성 추가
- Kafka 빈 설정
- 알림 발송용 NotificationKafkaProducer 공통 유틸 클래스 정의
=> feat: 알림 발송 템플릿 구현

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/Approve.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLine.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLineList.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveReceipt.java
closes #000
---
📌 개요
엔티티 수정
🔨 주요 변경 사항
- `approve`, `approve_line`, `approve_line_list` 상태 default를 1로 설정 (대기 상태로 설정)
- `approve_receipt` 가게 주소 추가 및 사용날짜를 `LocalDate`로 변경
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : 엔티티에서 default 값 설정 및 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/controller/RetentionContactQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/request/RetentionContactListRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/request/RetentionForecastRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/request/RetentionSupportRaw.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionContactDetailDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionContactItemDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionContactListResultDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionForecastItemDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/mapper/RetentionContactMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/mapper/RetentionStatisticsMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionContactQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionContactQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionStatisticsQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionSupportQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/retention/RetentionContactMapper.xml, momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/retention/query/controller/RetentionContactQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/query/service/RetentionContactQueryServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/query/service/RetentionStatisticsQueryServiceImplTest.java
closes #94 
closes #95
closes #196
---
📌 개요
🔨 주요 변경 사항
- RetentionContactQueryController
- RetentionForecastRequestDto
- RetentionContactItemDto
- RetentionContactListResultDto
- RetentionContactMapper
- RetentionContactQueryService
- RetentionContactQueryServiceImpl
- RetentionContactMapper
- RetentionContactQueryControllerTest
- RetentionContactQueryServiceImplTest
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> [feat #94 #95] 면담 기록 내역 조회 및 면담 요청 내역 조회 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java, momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/dto/request/PasswordChangeRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/dto/response/PasswordChangeResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
closes #114 
---
📌 개요
- 비밀번호 변경 기능 구현
- 사원은 현재 비밀번호, 새로운 비밀번호, 비밀번호 확인을 입력하여 비밀번호를 변경할 수 있다.
🔨 주요 변경 사항
- AuthController 및 AuthService 비밀번호 변경 메소드 구현
- /employees/change-password 엔드포인트 설정
✅ 리뷰 요청 사항
- 비밀번호 변경 기능 로직 확인
⭐ 관련 이슈
#114
=> feat: 비밀번호 변경 기능 구현

momentum-dao-be/build.gradle, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/service/FileService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DepartmentRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/EmployeeCSVResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/exception/EmployeeException.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/PositionRepository.java
closes #37 
---
📌 개요
- 사원 CSV 등록 기능 구현
🔨 주요 변경 사항
- opencsv 의존성 추가 (build.gradle 변경)
- presigned-url 요청에 csv 파일 허용
- 컨트롤러, 서비스 메서드, dto 추가
- 추후 개선 가능 사항: 권한도 CSV 일괄 등록 가능하게
(학력 등은 필드가 많은 1대 다라 어려울 듯. 필요하면 그쪽에도 CSV 등록 기능 지원 필요)
✅ 리뷰 요청 사항
- employee 생성 로직 적절한지
⭐ 관련 이슈
#37
=> feat: 사원 CSV 등록 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveReceiptDTO.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
closes #8
---
📌 개요
영수증 결재 내역에 주소 컬럼 추가 및 mapper 쿼리 수정
🔨 주요 변경 사항
- `ApproveReceiptDTO`(영수증 결재 내역 DTO)에 **storeAddress** 추가
- `ApproveDetailMapper`에 getReceiptDetail메서드에 **store_address** 컬럼 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#8
=> refactor : 영수증 결재 내역에 주소 컬럼 추가 및 mapper 쿼리 수정

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/ApproveCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApprovalConfirmRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalCancelCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalDecisionCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalDecisionCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/Approve.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLine.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLineList.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineListRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkApplyCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/BusinessTrip.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Overtime.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/RemoteWork.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Vacation.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Work.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkCorrection.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/BusinessTripRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/OvertimeRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/RemoteWorkRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/VacationRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/VacationTypeRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkCorrectionRepository.java
closes #10 
---
📌 개요
결재 승인, 반려 기능 구현하기
🔨 주요 변경 사항
- `ApproveCommandController`
- `/approval/descision` 경로로 승인, 반려 요청 받기
- `ApproveConfirmRequest` 생성하기 (승인, 반려 요청 객체) 
- `ApproveCommandService`, `ApproveCommandServiceImpl`
- `ApproveCancelService` : 취소 결재 관련된 서비스 로직 (근태 내역 변경)
- `WorkApplyService` : 결재 승인 시 근태 관련된 변경을 작성한 서비스 
- `ErrorCode` 에서 결재 관련 에러 코드 생성
- 엔티티 관련된 수정
- `Approve`, `ApproveLine`, `ApproveLineList`  각각의 엔티티에 수정 관련 메소드 추가하기 
- 근태 관련(BusinessTrip, Overtime, RemoteWork, Vacation, WorkCorrection` 엔티티에 Getter 어노테이션 추가 
- `ApproveRespository`, `ApproveLineRespository`, `ApproveLineListRespository`
✅ 리뷰 요청 사항
로직 점검
⭐ 관련 이슈
#10
=> feat : 결재 승인, 반려 기능 구현하기

momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/AdminEmployeeQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/EmployeeRoleDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/EmployeeRolesResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/mapper/UserRoleMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/EmployeeQueryService.java, momentum-dao-be/src/main/resources/mappers/organization/UserRoleMapper.xml
closes #256
---
📌 개요
- 특정 사원 권한 조회 기능 구현
🔨 주요 변경 사항
- 컨트롤러, 서비스, mapper 메서드, xml 쿼리, dto 작성
- SecurityConfig 수정
✅ 리뷰 요청 사항
- 응답 객체 적절한지
PS) empId의 존재 여부는 따로 검증하지 않고 있음.
MyBatis 쪽의 list 조회 형태여서 "존재하지 않는 사원"과 "아무런 권한이 없는 사원"이 구분되지 않는 상태
필요 시 관련 로직 추가
⭐ 관련 이슈
#256
=> feat: 특정 사원 권한 조회 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/controller/HolidayQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/request/HolidaySearchDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/request/HolidaySearchRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/response/HolidayGetDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/response/HolidayGetResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/mapper/HolidayMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/service/HolidayQueryService.java, momentum-dao-be/src/main/resources/mappers/organization/HolidayMapper.xml
closes #262 
---
📌 개요
- 휴일 조회 기능 구현
- 관리자는 회사의 휴일들을 검색조건을 걸어서 조회할 수 있다.
🔨 주요 변경 사항
- HolidayQueryService.getHolidays 메소드 구현
- HolidayQueryController.getHolidays 메소드 구현
✅ 리뷰 요청 사항
- 휴일 조회 기능 로직 확인 
- 커밋 메세지는 잘못 적었습니다.
⭐ 관련 이슈
#262
=> feat: 휴일 조회 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveLineListRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveLineRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveRefRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveCancelRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveProposalRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveReceiptRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/BusinessTripRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/OvertimeRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/RemoteWorkRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/VacationRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/WorkCorrectionRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/response/ReceiptOcrResultResponse.java
closes #9
---
📌 개요
결재 문서 작성 요청, 응답 객체에 description  추가
🔨 주요 변경 사항
- request 객체에 스웨거에서 사용되는 description  추가
- `ApproveLineListRequest`
- `ApproveLineRequest`
- `ApproveRefRequest`
- `ApproveRequest`
- `ApproveCancelRequest`
- `ApproveProposalRequest`
- `ApproveReceiptRequest`
- `BusinessTripRequest`
- `OvertimeRequest`
- `RemoteWorkRequest`
- `VacationRequest`
- `WorkCorrectionRequest`
- response 객체에 스웨거에서 사용되는 description  추가
- `ReceiptOcrResultResponse` 
✅ 리뷰 요청 사항
⭐ 관련 이슈
#9
=> refactor : 결재 문서 작성 요청, 응답 객체에 description  추가

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/ApproveQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/EmployeeLeaderDto.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ApproveMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/ApproveQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImplTest.java
closes #218 
---
📌 개요
결재 문서 작성 시 팀장을 default로 설정하기 위해 사원의 팀장 조회하기
🔨 주요 변경 사항
- `ApproveQueryController`
- `/approval/leader`로 엔드포인트 설정
- 테스트 완료
- `ApproveQueryService`,  `ApproveQueryServiceImpl`
- 팀장을 조회하는 `getEmployeeLeader` 메소드 생성
- 테스트 완료 
- `ApprvoeMapper.java`, `ApproveMapper.java`
- `findEmployeeLeader` 메소드 생성 및 쿼리 작성
- `EmployeeLeaderDto` 
- 팀장의 사번과 이름 
✅ 리뷰 요청 사항
로직 점검 
⭐ 관련 이슈
#218
=> feat : 사원의 팀장 조회하기

momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/service/AnnouncementCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/announcement/query/dto/response/AnnouncementDetailDto.java, momentum-dao-be/src/main/java/com/dao/momentum/common/s3/S3Service.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/controller/FileController.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/request/AttachmentRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/request/DownloadUrlRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/response/AttachmentDto.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/response/DownloadUrlResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/service/FileService.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/domain/aggregate/File.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java, momentum-dao-be/src/main/resources/mappers/announcement/query/mapper/AnnouncementQueryMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/announcement/command/application/controller/AnnouncementCommandControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/announcement/command/application/service/AnnouncementCommandServiceTest.java, momentum-dao-be/src/test/java/com/dao/momentum/announcement/query/controller/AnnouncementQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/announcement/query/service/AnnouncementQueryServiceTest.java, momentum-dao-be/src/test/java/com/dao/momentum/file/command/application/controller/FileControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/file/command/application/service/FileServiceTest.java, momentum-dao-be/src/test/java/com/dao/momentum/organization/company/query/service/CompanyQueryServiceTest.java
closes #311 closes #312 
---
📌 개요
파일 엔티티에 name 컬럼 추가 -> 공지사항 업로드, 수정, 조회 로직 리팩토링, 
S3 PresignedURL 생성 시 Content-Disposition 헤더 설정 해제
🔨 주요 변경 사항
- 공지사항 업로드, 수정, 조회 로직에서 File 엔티티에 추가된 name 필드 반영
- 관련 테스트 코드 수정
- S3 PresignedURL 생성 시 Content-Disposition 헤더 설정 제거(클라이언트가 직접 blob 형식으로 받아와서 다운로드 url을 생성하는 식으로 처리할 예정)
=> refactor: 파일 엔티티에 name 컬럼 추가 -> 공지사항 업로드, 수정, 조회 로직 리팩토링, S3 PresignedURL 생성 시 Content-Disposition 헤더 설정 해제

momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/MyWorkDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/MyWorkListResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/work/query/service/WorkQueryServiceTest.java
closes #000
---
📌 개요
- 본인 출퇴근 내역 조회(캘린더용) 기능이 작동하지 않아 수정
- 관리자 출퇴근 내역 조회와 동일한 DTO를 공유하여 작성했으나, 해당 DTO의 수정 사항을 반영하지 않은 것이 원인
- 본인 출퇴근 조회용 DTO를 분리하는 방향으로 수정
- empId 등 일부 필드는 필요 없을 것으로 보임 (시간 남으면 수정 예정)
🔨 주요 변경 사항
- MyWorkDTO, MyWorkListResponse 생성, 쿼리 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#11
=> fix: 본인 출퇴근 내역 조회 수정

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveFileDTO.java, momentum-dao-be/src/main/resources/mappers/approve/AdminApproveMapper.xml, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml, momentum-dao-be/src/main/resources/mappers/approve/DraftApproveMapper.xml, momentum-dao-be/src/main/resources/mappers/approve/ReceivedApproveMapper.xml
closes #000
---
📌 개요
첨부 파일 관련된 부분에 name 속성 추가 및 order 변경
🔨 주요 변경 사항
- 상세 조회 시 첨부 파일 이름을 함께 조회할 수 있게 수정 
- `ApproveFileDTO`에 name 필드 추가
- 목록 조회 시 상태가 `대기`인 결재 문서가 먼저 목록에 노출될 수 있게 수정 
- 결재 문서 작성 시 name도 함께 추가할 수 있도록 수정 
✅ 리뷰 요청 사항
⭐ 관련 이슈
#3 #6 #7 #8 #9
=> fix : 첨부 파일 관련된 부분에 name 속성 추가

momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/aggregate/RetentionSupport.java
closes #000
---
📌 개요
- 컴파일 에러 해결 (pull 했을 때 오류 안나도록 임시 조치)
🔨 주요 변경 사항
- DTO 쪽 임시로 형변환 (RetentionSupport)
- 올바른 로직으로 돌아가게 하려면 DTO 및 메서드들 수정 필요
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> [fix] run 실패 문제 해결

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/RemainingVacationQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
closes #000
---
📌 개요
endpoint 변경 및 조회 관련 오류 수정
🔨 주요 변경 사항
- 결재 작성 시 조회되는 사원의 리프레시 휴가 수와 연차 수 조회 endpoints 변경 및 security에 해당 위치 설정
- 결재 상세 보기에서 휴가 종류가 이상하게 조회 되는 부분 해결 (`vacation_type_id`를 `vacation_id`로 쓰고 있었음)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#8 #9
=> refactor : endpoint 변경 및 조회 관련 오류 수정

momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractRetentionService.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/calculator/RetentionScoreCalculatorImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkRetentionService.java
closes #000
---
📌 개요
- 근속 지원 점수 계산 메서드 반영
🔨 주요 변경 사항
- 연봉 상승, 발령, 승진, 근속 연수, 근태 메서드 `RetentionScoreCalculatorImpl `에 반영
- 메서드명 통일성 있게 수정
✅ 리뷰 요청 사항
- 감점하는 점수에 소수점이 포함된 경우가 있어, double 혹은 BigDecimal로 자료형 수정 필요할 듯 (예시 하단 이미지)
⭐ 관련 이슈
#369
=> feat: 근속 지원 점수 계산 메서드 반영 

momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
closes #000
---
📌 개요
- 사원 목록 조회 권한 필터 조건 수정
🔨 주요 변경 사항
- xml 쿼리 수정
- 최고 관리자이자 팀장일 때, 팀장으로 권한 필터를 걸면 권한이 "팀장"으로만 조회되었음 -> "최고 관리자, 팀장"으로 모두 나오도록 수정
- WHERE 절이 아닌 HAVING 절에서 필터링
✅ 리뷰 요청 사항
⭐ 관련 이슈
#34
=> fix: 사원 목록 조회 쿼리 수정

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/ApproveQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ApproveDetailMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml, momentum-dao-be/src/main/resources/mappers/approve/ReceivedApproveMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImplTest.java
closes #8
---
📌 개요
현재 어떤 사원이라도 결재 문서를 조회할 수 있어서, 
이를 막기 위해 조회 가능 한 결재만 조회 할 수 있게 수정
🔨 주요 변경 사항
- 사원 본인이 받은 문서(참조자 or 결재자), 작성한 문서인 경우에만 조회 가능 (controller, mapper, service 모두 수정)
- 마스터 관리자인 경우에는 모든 문서 상세 조회 가능하게 수정  (controller, mapper, service 모두 수정)
- 결재 상세 조회 테스트 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#8
=> fix : 조회 가능 한 결재만 조회 할 수 있게 수정

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/ApproveCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalDecisionCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveCancelRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineListRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveProposalRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveReceiptRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveRefRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/file/command/domain/repository/FileRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/BusinessTripRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/OvertimeRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/RemoteWorkRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/VacationRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkCorrectionRepository.java
closes #331
---
📌 개요
결재 문서 회수 기능 구현
🔨 주요 변경 사항
- `ApproveCommandController`에 `/documents/{documentId}`로 endpoint 작성
- 결재가 시작되지 않은 건에 한 해 결재 문서 회수 기능 구현
- 결재 문서 회수 시 결재 form, 결재선, 결재선 목록, 참조자, 결재 문서가 모두 삭제될 수 있게 설정
- 관련된 13개의 repository(결재 문서 8개 + 결재선 + 결재선 목록 + 참조자 + 파일 + 결재)에 delete 메소드 작성
✅ 리뷰 요청 사항
⭐ 관련 이슈
#331
=> feat : 결재 문서 회수 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveRefDTO.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
closes #8 
---
📌 개요
결재 상세 조회 시 참조자의 empId도 조회할 수 있게 수정
🔨 주요 변경 사항
- `ApproveRefDTO`에서 empId가 같이 조회 되게 수정
- `ApproveDetailMapper`에서 emp_id 같이 조회 되게 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#8
=> refactor : 결재 상세 조회 시 참조자의 empId도 조회할 수 있게 수정

momentum-dao-be/src/main/resources/application.yml
closes #000
---
📌 개요
- `application.yml` 설정 수정
🔨 주요 변경 사항
- 아래의 WARN 로그 뜨지 않도록 조치
- `2025-07-17T11:14:56.941+09:00  WARN 36028 --- [  restartedMain] org.hibernate.orm.deprecation            : HHH90000025: MariaDBDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)`
- `deprecation`에 대한 경고로 판단되어 수정함
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: 백엔드 서버 WARN 로그 해결

momentum-dao-be/build.gradle, momentum-dao-be/src/main/java/com/dao/momentum/common/config/RedisConfig.java, momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/resources/application.yml
k8s ingress 분기용 context-path 설정, spring actuator health endpoint 활성화, redis ssl 연결 설정
closes #000
---
📌 개요
- k8s ingress 분기용 context-path 설정(/api/backend-batch/v1)
- spring actuator health endpoint 활성화(+security filter permit all)
- redis ssl 연결 설정(elasticache)
=> chore: k8s ingress 분기용 context-path 설정, spring actuator health endpoint 활성화, redis ssl 연결 설정
