be15-fin-project/be15-fin-DAO-Momentum-BE

momentum-dao-be/src/main/java/com/dao/momentum/common/dto/ApiResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/common/dto/Pagination.java
closes #4 
---
📌 개요
공통 사용하는 클래스인 ApiResponse 및 Pagination 생성
🔨 주요 변경 사항
ApiResponse 및 Pagination 생성
✅ 리뷰 요청 사항
ApiResponse 및 Pagination 생성 확인
⭐ 관련 이슈
#4
=> [feat #4] ApiResponse 및 Pagination 생성

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
📌 개요
🔨 주요 변경 사항
ErrorCode 및 GlobalExceptionHandler 구현
✅ 리뷰 요청 사항
ErrorCode 및 GlobalExceptionHandler 구현
=> [feat] ErrorCode 및 GlobalExceptionHandler 구현

momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/WorkCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/dummy.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/IsNormalWork.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Work.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkType.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkTypeRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/infrastructure/repository/JpaWorkRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/infrastructure/repository/JpaWorkTypeRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes null
---
- 근태 관리 기능 구현을 위한 초기 세팅
- entity 등록
- controller, service, mapper, repository 추가
null
=> [init] 근태 관리 기능 구현을 위한 초기 세팅

momentum-dao-be/build.gradle, momentum-dao-be/src/main/java/com/dao/momentum/common/config/ModelMapperConfig.java, momentum-dao-be/src/main/java/com/dao/momentum/common/dump.java, momentum-dao-be/src/main/java/com/dao/momentum/common/jwt/RestAccessDeniedHandler.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/dummy.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/EmployeeRoles.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Gender.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Status.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/UserRole.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/UserRoleName.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/JpaEmployeeRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/EmployeeQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/EmployeeQueryService.java
📌 개요
사원 기능 구현을 위한 초기 세팅
🔨 주요 변경 사항
entity, controller, service, repository 생성
✅ 리뷰 요청 사항
클래스 오류 확인
⭐ 관련 이슈
=> [init] 사원 기능 구현을 위한 초기 세팅

momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/IsRead.java, momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/Notification.java, momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/NotificationTemplate.java
=> init: 알림, 알림 템플릿 엔티티 생성

.idea/workspace.xml, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionContact.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionInsight.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionRound.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionSupport.java
closes 
---
📌 개요
🔨 주요 변경 사항
- RetentionContact
- RetentionInsight
- RetentionRound
- RetentionSupport
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> init : retention entity update

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/dummy.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/Approve.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLine.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLineList.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveProposal.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveReceipt.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveRef.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveType.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/IsConfirmed.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/IsRequiredAll.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ReceiptType.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/temp/command/application/controller/dummy.java
closes #000
---
📌 개요
결재 관련 엔티티 생성
🔨 주요 변경 사항
- Approve : 결재 엔티티 (ApproveType이 enum으로 들어감)
- ApproveLine : 결재선 엔티티 (IsRequiredAll이 enum으로 들어감)
- ApproveLineList : 결재선 목록 엔티티 
- ApproveProposal : 품의 결재 엔티티
- ApproveReceipt : 결재 영수증 엔티티 (ReceiptType이 enum으로 들어감)
- ApproveRef : 참조 엔티티 (IsConfirmed이 enum으로 들어감)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> init : 결재 엔티티 생성

momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/domain/aggregate/Contract.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/domain/aggregate/ContractType.java
📌 개요
Contract 엔티티 생성
🔨 주요 변경 사항
Contract 엔티티 생성
✅ 리뷰 요청 사항
필드 자료형 일치 여부
⭐ 관련 이슈
#
=> [init] Contract 엔티티 생성

momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/aggregate/Department.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/aggregate/DeptHead.java
📌 개요
- Department 엔티티 DeptHead 엔티티 생성
🔨 주요 변경 사항
- Department 엔티티 DeptHead 엔티티 생성
- @Validation 관련 어노테이션 추가
✅ 리뷰 요청 사항
- 필드 변수형 체크
⭐ 관련 이슈
=> Department 엔티티 생성

momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/Company.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/Holiday.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/IpAddress.java
📌 개요
- Compay, IpAddress, Holiday 엔티티 구현
🔨 주요 변경 사항
- Compay, IpAddress, Holiday 엔티티 구현
- Department 부분은 커밋이 꼬여서 제외하고 봐주시면 될 것 같습니다.
- department 쪽 conflict 해결하고 merge 예정
✅ 리뷰 요청 사항
- 엔티티 필드 데이터 유형 검사
⭐ 관련 이슈
=> Compay, IpAddress, Holiday 엔티티 구현

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/Approve.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/infrastructure/api/NaverOcrApi.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/NotExistTabException.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/AdminApproveController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/request/ApproveListRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/request/PageRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/response/ApproveResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/AdminApproveMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java, momentum-dao-be/src/main/resources/mappers/approve/AdminApproveMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/AdminApproveControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/AdminApproveServiceImplTest.java
closes #3
---
📌 개요
전체 결재 문서 조회 기능 구현 (마스터 관리자)
🔨 주요 변경 사항
- Controller 작성 완료
- `AdminApproveController` 작성
- `AdminApproveControllerTest` 작성
- Service 작성 완료
- `AdminApproveService` 작성 (인터페이스)
- `AdminApproceServiceImpl` 작성 (구현 클래스)
- 결재 탭과 관련해서 errorCode 작성 및 핸들러 처리 완료
- Mapper 작성 완료 
- `AdminApproveMapper.xml`, `AdminApproveMapper.java` 작성 
- 전체 결재 목록 조회 메서드, 결재 목록 조회시 개수를 세는 메서드 작성 
- DTO
- `ApproveDTO` 
- `ApproveResponse` : 결재 DTO 객체와 페이징 관련 객체를 가지고 있는 객체
- `ApproveRequest` : 결재 요청 객체 생성
- 필요 없는 더미 데이터들 삭제
✅ 리뷰 요청 사항
로직 점검
⭐ 관련 이슈
#3
=> feat : 전체 결재 문서 조회 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/PositionCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/dummy.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/request/PositionCreateRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/response/PositionCreateResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/service/PositionCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/aggregate/Position.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/PositionRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/infrastructure/repository/JpaPositionRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/exception/PositionException.java, momentum-dao-be/src/test/java/com/dao/momentum/organization/position/command/application/service/PositionCommandServiceTest.java
closes #101 
---
📌 개요
- 직위 등록 기능 구현
🔨 주요 변경 사항
- 직위 등록 Controller, Service 메소드 구현
- PositionRepository 작성
- 예외처리 추가
- 테스트코드 작성
✅ 리뷰 요청 사항
- 직위 등록 로직 검사
- 테스트코드 로직 검사
⭐ 관련 이슈
#101
=> feat: 직위 등록 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java, momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
closes #113 
---
📌 개요
- 사원의 로그아웃 기능 구현
🔨 주요 변경 사항
- AuthController 및 AuthService의 로그아웃 메소드 구현
✅ 리뷰 요청 사항
- 로그아웃 로직 확인
⭐ 관련 이슈
#113
=> feat: 로그아웃 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/evaluation/command/domain/aggregate/EvalPrompt.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/command/domain/aggregate/HrWeight.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionInsight.java
closes #000
---
📌 개요
🔨 주요 변경 사항
- EvalPrompt.java
- HrWeight.java
- RetentionInsight.java
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> init ERD 수정에 따른 entity 수정

momentum-dao-be/src/test/java/com/dao/momentum/common/auth/application/controller/AuthControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/common/auth/application/service/AuthServiceTest.java
📌 개요
- 로그인 및 로그아웃 테스트코드 작성
🔨 주요 변경 사항
authControllerTest 및 authServiceTest 작성
✅ 리뷰 요청 사항
- 테스트코드 로직 확인
⭐ 관련 이슈
#2 #113
=> test: 로그인 및 로그아웃 테스트코드 작성

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveCancel.java
closes #000
---
📌 개요
취소 결재 엔티티 추가
🔨 주요 변경 사항
- 취소 결재 테이블 생성으로 인한 엔티티 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> init : 취소 결재 엔티티 추가

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/EmployeeInfoUpdateRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/EmployeeInfoDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/EmployeeInfoUpdateResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java
closes #41
---
📌 개요
- 사원 기본 정보 수정 기능 구현
🔨 주요 변경 사항
- 컨트롤러, 서비스 메서드, dto 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#41
=> feat: 사원 기본 정보 수정 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/WorkCommandController.java, momentum-dao-be/src/test/java/com/dao/momentum/work/command/application/controller/WorkCommandControllerTest.java
closes #000
---
📌 개요
- 컨트롤러 http 응답 코드 수정
🔨 주요 변경 사항
- 생성 시 ok -> created
- 이에 따라 테스트 코드도 함께 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: http 응답 코드 수정

momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java
closes #000
---
📌 개요
- 불필요한 import 문 삭제
🔨 주요 변경 사항
✅ 리뷰 요청 사항
회고 쓰다가 발견한 간단한 수정사항 PR 올립니다.
aceept 누르신 분이 바로 merge까지 해주시면 될 듯해요.
⭐ 관련 이슈
#
=> refactor: workmapper 불필요한 import 문 삭제

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DepartmentRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/infrastructure/repository/JpaDepartmentRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/exception/DepartmentException.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/AppointCreateRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/AppointCreateResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/AppointDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Appoint.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/AppointType.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/AppointRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/JpaAppointRepository.java
closes #000
(배치 작업까지 구현 시 close)
---
📌 개요
- 사원 발령 등록 기능 구현
🔨 주요 변경 사항
- 컨트롤러, 서비스, repository 메서드 작성, dto 추가
- department repository 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#40
=> feat: 사원 발령 등록 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/AdminEmployeeQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointSearchDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointSearchRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointType.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/AppointDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/AppointListResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/mapper/AdminEmployeeMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/AdminEmployeeQueryService.java, momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
closes #170 
---
📌 개요
- 사원 발령 내역 조회 기능 구현
🔨 주요 변경 사항
- 컨트롤러, 서비스, mapper 메서드, dto, xml 쿼리 작성
✅ 리뷰 요청 사항
⭐ 관련 이슈
#170
=> feat: 사원 발령 내역 조회 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/ApproveCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/dummy.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/response/ReceiptOcrResultResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/OcrService.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/OcrServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/infrastructure/api/NaverOcrApi.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/OcrRequestFailedException.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java, momentum-dao-be/src/main/resources/application.yml
closes #191
---
📌 개요
영수증 결재 내역 추출 기능 구현
🔨 주요 변경 사항
- `application.yml` : 클로바 api 관련 url과 비밀키 추가
- `ReceiptOcrResultResponse` : 영수증 추출 결과 응답 객체
- `NaverOcrApi` : 네이버 클로바 api 연결과 관련된 클래스
- `OcrService`, `OcrServiceImpl` 
- `ApproveCommandController`
- 예외 처리 관련된 부분
- `OcrRequestFailedException` : api 요청 실패 시 발생하는 예외
- `ErrorCode` : api 요청 실패시 에러 코드 추가
- `GlobalExceptionHandler` : api 핸들러 처리 추가
✅ 리뷰 요청 사항
로직 점검
⭐ 관련 이슈
#191
=> feat : 영수증 결재 내역 추출 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/query/dto/request/AdminContractSearchDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/query/dto/request/AdminContractSearchRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/query/dto/response/AdminContractDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/aggregate/Department.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/controller/DepartmentQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/mapper/DepartmentMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/WorkSearchDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/WorkSearchRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes #000
---
📌 개요
- work 쪽 DTO에서 empNo 자료형 변경 (long -> String)
🔨 주요 변경 사항
- 상단 변화에 따라 파생된 변경 사항 (쿼리 수정 등)
- request -> DTO 변환 로직을 DTO 쪽으로 이관 (request의 toDTO -> DTO의 fromRequest)
- run 실패의 원인이 되는 department 쪽 불필요한 import 문 삭제
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: empNo 자료형 변경

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveFileDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/OvertimeDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
closes #8
---
📌 개요
결재 상세 내역 조회 기능 추가 및 수정
🔨 주요 변경 사항
- `ApproveFileDTO`에서 url을 s3Key로 변경
- `OvertimeDTO `에 근무 유형을 계산하는 로직 추가
- `ApproveQueryImpl`에 근무 유형 계산 메서드(DTO에 있는) 넣기
✅ 리뷰 요청 사항
⭐ 관련 이슈
#8
=> feat : 결재 상세 내역 조회 기능 추가 및 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/controller/RetentionContactCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/controller/dummy.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/CreateRetentionContactRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/RetentionContactCreateDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/response/RetentionContactResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/service/RetentionContactCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/service/RetentionContactCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionContact.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/repository/RetentionContactRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/repository/RetentionContactRepositoryImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/command/infrastructure/repository/JpaRetentionContactRepository.java
closes #96 
---
📌 개요
🔨 주요 변경 사항
**면담 요청 기능**
- RetentionContactCommandController
- RetentionContactCommandServiceImpl
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> feat : 면담 요청 기눙 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/dto/request/EvalFactorScoreDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalResponseService.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalResponseServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreCalculator.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreCalculatorImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreService.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/aggregate/EvalResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/aggregate/EvalScore.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/repository/EvalResponseRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/repository/EvalScoreRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/repository/EvalScoreRepositoryImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/infrastructure/repository/JpaEvalResponseRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/infrastructure/repository/JpaEvalScoreRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/controller/HrObjectionProcessController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/dto/request/HrObjectionProcessRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/dto/response/HrObjectionProcessResponseDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/facade/HrObjectionProcessFacade.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/service/HrObjectionService.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/service/HrObjectionServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/domain/aggregate/HrObjection.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/domain/repository/HrObjectionRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/infrastructure/repository/HrObjectionJpaRepository.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/command/application/service/EvalResponseServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreCalculatorImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/command/application/service/HrObjectionServiceImplTest.java
closes #85
---
📌 개요
🔨 주요 변경 사항
facade를 통한 인사 평가 이의 제기 승인/반려 기능 구현
요인별 점수 수정을 통한 종합 점수 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> feat :  인사 평가 이의 제기 승인/반려 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/VacationTimeCommandService.java
closes #000
---
📌 개요
- 사원 관리 security config 추가
🔨 주요 변경 사항
- security config 추가
- 연차 지급일수 계산 수정 (3년차에게 1일 추가 지급이 되지 않던 문제)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: 사원 관리 security config 추가

momentum-dao-be/build.gradle, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/controller/RetentionForecastController.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionForecastCreateRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionInsightDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionSupportDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/response/RetentionForecastCreateResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/controller/RetentionSupportExcelDownloadController.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/RetentionSupportExcelDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionAverageScoreDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/mapper/RetentionSupportExcelMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadService.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/util/ExcelGenerator.java, momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportExcelMapper.xml
closes #238
---
📌 개요
🔨 주요 변경 사항
swagger용 어노테이션 추가
**근속 전망 엑셀 다운로드 기능 구현**
새 의존성 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> feat : 근속 전망 엑셀 다운로드 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiExcelDownloadController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiExelRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiListRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/response/KpiExcelDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/mapper/KpiExcelMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiExcelDownloadService.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiExcelDownloadServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/util/KpiExcelGenerator.java, momentum-dao-be/src/main/resources/mappers/evaluation/KpiExcelMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/service/KpiExcelDownloadServiceImplTest.java
closes #243
---
📌 개요
🔨 주요 변경 사항
**kpi 엑셀 다운로드 기능 구현**
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> feat : KPI 엑셀 다운로드 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/controller/ExcelEvaluationDownloadController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/request/PeerEvaluationExcelRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/PeerEvaluationExcelDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/ExcelEvaluationQueryMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvalFormQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/ExcelEvaluationDownloadService.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/ExcelEvaluationDownloadServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/util/PeerEvaluationExcelGenerator.java, momentum-dao-be/src/main/resources/mappers/evaluation/ExcelEvaluationQueryMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/ExcelEvaluationDownloadServiceImplTest.java
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#242
=> feat: 평가별 엑셀 다운로드 기능 - 사원간 평가

momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRolesRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/UserRoleRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/JpaEmployeeRolesRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/JpaUserRoleRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/AdminEmployeeQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/UserRoleDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/UserRolesResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/mapper/UserRoleMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/EmployeeQueryService.java, momentum-dao-be/src/main/resources/mappers/organization/UserRoleMapper.xml
closes #107 
---
📌 개요
- 권한 목록 조회 기능 구현
🔨 주요 변경 사항
- 컨트롤러, 서비스 메서드 작성, dto, xml 쿼리 추가
- 엔드포인트 security 설정
- 불필요한 import 문 삭제
✅ 리뷰 요청 사항
⭐ 관련 이슈
#107
=> feat: 권한 목록 조회 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/RoleUpdateRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/RoleUpdateResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/EmployeeRoles.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRolesRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/UserRoleRepository.java
closes #108
---
📌 개요
- 권한 수정 기능 구현
🔨 주요 변경 사항
- 컨트롤러, 서비스, repository 메서드, dto 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#108
=> feat: 권한 수정 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/controller/ContractCommandController.java
closes #000
---
📌 개요
- 컨트롤러 응답 수정
🔨 주요 변경 사항
- 작업 시 일관성을 위해 ApiResponse 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: ApiResponse로 감싸지 않은 응답 수정

momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/EmployeeRoleDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/EmployeeRolesResponse.java
closes #000
---
📌 개요
- 사원 권한 swagger 어노테이션 추가
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> docs: 사원 권한 swagger 어노테이션 추가

momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkEndResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkStartResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkSummaryDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/IsNormalWork.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkListResponse.java
closes #000
---
📌 개요
- 근무 컨텍스트에 swagger 어노테이션 추가
🔨 주요 변경 사항
- response 객체에 대한 swagger 어노테이션 추가
- query에서 command 쪽의 enum을 의존하던 문제 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: 근무 swagger 어노테이션 추가

momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/EmployeeRecordsUpdateRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/CSVService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/EmployeeRecords.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/RecordType.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/Order.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDetailsDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDetailsResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes #266
---
📌 개요
- 출퇴근 상세 내용 조회 기능 구현
🔨 주요 변경 사항
- 컨트롤러, 서비스, mapper 메서드, xml 쿼리, dto 작성
- command, query 의존성 제거 (enum 클래스)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#266
=> feat: 출퇴근 상세 내용 조회 기능 구현

momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/EvalFormQueryServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/controller/KpiStatisticsControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryServiceImplTest.java
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> test : 예외처리 변경으로 인한 테스트 코드 오류 수정

momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/PositionCommandController.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/infrastructure/repository/JpaPositionRepository.java
📌 개요
- 불필요 메소드 및 import문 제거
🔨 주요 변경 사항
- Department 컨텍스트 코드 수정
✅ 리뷰 요청 사항
- 코드 확인
=> [refactor] 불필요 메소드 및 import문 제거

momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiRequestQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiStatisticsController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiEmployeeSummaryRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiListRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiRequestListRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiStatisticsRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiTimeseriesRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiStatisticsServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRepository.java, momentum-dao-be/src/main/resources/mappers/evaluation/KpiQueryMapper.xml, momentum-dao-be/src/main/resources/mappers/evaluation/KpiStatisticsMapper.xml
closes #000
---
📌 개요
🔨 주요 변경 사항
- 통계 조회에 부서별, 직위별 필터링 추가
- empId 필터링 empNo필터링으로 변경
- empId 호출 방식 통일
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : 필터링 변경 및 empId 호출 방식 변경

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/AdminApproveQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/resources/mappers/approve/AdminApproveMapper.xml
closes #000
---
📌 개요
결재 조회 권한 설정 수정하기
🔨 주요 변경 사항
- 결재 조회 권한에서 `@PreAuthorize("hasAuthority('MASTER')")` 없애고 SecurityConfig에 url로 설정
- 결재 탭에 'ALL'이라는 탭 추가 (전체 검색을 위함)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#3
=> refactor : 결재 조회 권한 설정 수정

momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/VacationTypeDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/VacationTypeResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkTypeDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkTypeResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes #000
---
📌 개요
- 근무 유형, 휴가 유형 조회 기능 작성
- 출퇴근 내역 조회 시 필터 옵션 제공에 필요
- 출퇴근 내역 조회 쿼리 수정
🔨 주요 변경 사항
- 컨트롤러, 서비스, mapper 메서드, xml 쿼리, dto 작성
- 출퇴근 내역 조회 쿼리 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#12
=> [feat] 근무 유형, 휴가 유형 조회 기능 작성

momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
closes #000
---
📌 개요
- 부서 없는 직원이 조회되지 않는 문제 수정
🔨 주요 변경 사항
- JOIN -> LEFT JOIN 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#34
=> fix: 사원 목록 조회 쿼리 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/controller/EvaluationManageController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/request/EvaluationFormPropertyRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationFormDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationFormPropertyDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationTypeDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationTypeTreeResponseDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/EvaluationManageMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationManageService.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationManageServiceImpl.java, momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationManageMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/controller/EvaluationManageControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/EvaluationManageServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/organization/company/query/service/CompanyQueryServiceTest.java
closes #302
closes #304 
---
📌 개요
🔨 주요 변경 사항
- 평가 종류 트리 조회 기능 구현
- 평가 양식 별 요인 조회 기능 구현
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> feat 평가 종류 트리 조회 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/AppointCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointSearchDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointSearchRequest.java, momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
closes #000
---
📌 개요
- 발령 내역 조회 쿼리 수정
🔨 주요 변경 사항
- 필터 조건 사원ID -> 사번 수정 (사원ID는 트리로 선택해야 적용 가능)
- 발령 및 계약서 에러코드 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#170
=> refactor: 발령 내역 조회 쿼리 수정

momentum-dao-be/src/test/java/com/dao/momentum/organization/company/query/service/CompanyQueryServiceTest.java
📌 개요
🔨 주요 변경 사항
- 회사 정보 조회 테스트 수정
✅ 리뷰 요청 사항
-테스트코드 확인
⭐ 관련 이슈
=> [test] 회사 정보 조회 테스트 수정

momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/mapper/HolidayMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/service/HolidayQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/AttendanceDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/AttendanceResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/IsAttended.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/VacationTypeEnum.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkTypeName.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java, momentum-dao-be/src/main/resources/mappers/organization/HolidayMapper.xml, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes #000
---
📌 개요
🔨 주요 변경 사항
- 퇴근 모달에 당일 출근 시간 띄울 수 있도록 응답 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#13
=> refactor: 출퇴근 등록 쿼리 수정

momentum-dao-be/src/test/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImplTest.java
closes #9
---
📌 개요
결재 생성 코드에서 에러 발생 
🔨 주요 변경 사항
- 결재 생성 시 알림을 보내는 과정에서 추가된 코드를 바탕으로 테스트 코드 수정
- `EmployeeRespository`와 `NotificationKafkaProducer` Mock으로 주입 한 뒤 테스트 코드 수정 
✅ 리뷰 요청 사항
⭐ 관련 이슈
#9
=> test : 테스트 코드 수정

momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/controller/HrObjectionQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/request/MyHrEvaluationListRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/request/MyObjectionListRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/request/MyObjectionRaw.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/response/MyObjectionItemDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/mapper/HrObjectionMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/HrObjectionQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/HrObjectionQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationHrMapper.xml, momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationTaskMapper.xml, momentum-dao-be/src/main/resources/mappers/evaluation/HrObjectionMapper.xml, momentum-dao-be/src/main/resources/mappers/evaluation/MyObjectionMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/controller/HrObjectionQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/HrObjectionQueryServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImplTest.java
closes #318 
---
📌 개요
🔨 주요 변경 사항
- 인사 평가 내역 조회시 회차 필터 추가
- 상세 조회 기능 구현
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> feat: 인사 평가 이의제기 요청 상세 조회 추가

momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/MyWorkDTO.java, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes #000
---
📌 개요
- 본인 출퇴근 조회 (캘린더) 수정 
🔨 주요 변경 사항
- 함께 넘기는 필드 값에 휴게 시간 및 근무 시간 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#11
=> refactor: 본인 출퇴근 조회 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java, momentum-dao-be/src/main/resources/mappers/announcement/query/mapper/AnnouncementQueryMapper.xml
📌 개요
공지사항 목록 조회 -> 하위 부서까지 한번에 목록 조회, 
SecurityConfig EndPoint상 누락된 "/" 추가
=> refactor: 공지사항 목록 조회 -> 하위 부서까지 한번에 목록 조회

momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionForecastCreateRequest.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/response/RetentionForecastCreateResponse.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/facade/RetentionForecastFacade.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/repository/RetentionRoundCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/repository/RetentionRoundCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/repository/RetentionRoundRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/RetentionSupportRaw.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionForecastItemDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionSupportDetailDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportMapper.xml
closes #000
---
📌 개요
🔨 주요 변경 사항
- 근속 전망 회차 상세조회 정보 추가
- 점수, 근속 연차, 상급자 정보 등
- 해당 상세 조회를 통한 면담 요청 바로 이동 기능 고려중
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : 근속 전망 상세 조회 정보 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java, momentum-dao-be/src/main/java/com/dao/momentum/email/service/EmailService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java, momentum-dao-be/src/main/resources/templates/email/init-password.html
📌 개요
- 이메일 처리 메소드 수정
🔨 주요 변경 사항
- EmailService 외부에서 의존성을 주입받는 메소드 추가
✅ 리뷰 요청 사항
- 기존 메소드와 로직 비교
⭐ 관련 이슈
#
=> refactor: 이메일 처리 메소드 수정

momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes #000
---
📌 개요
- 부서 조회 조건 수정
🔨 주요 변경 사항
- 부서 필터로 검색 시 하위 부서까지 조회 가능하도록 쿼리 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#12, #34
=> refactor:  사원 목록 조회, 출퇴근 목록 조회 시 부서 필터링 수정

momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/response/AttachmentDto.java, momentum-dao-be/src/main/resources/mappers/announcement/query/mapper/AnnouncementQueryMapper.xml
📌 개요
공지사항 상세 조회 -> 첨부파일 리스트 Dto 안에 fileId 추가
🔨 주요 변경 사항
- 공지사항 수정 시 기존에 등록해놨던 공지사항 리스트를 추적하기 위해 fileId 필드를 상세조회 응답에 추가
=> refactor: 공지사항 상세 조회 -> 첨부파일 리스트 Dto 안에 fileId 추가

momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationTaskMapper.xml
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : 평가 제출 목록 정렬 조건 수정

momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractCommandService.java
- 계약서 등록 파일 업로드 수정
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> fix: 계약서 등록 시 파일명 추가

momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
📌 개요
- position 엔드포인트 권한 수정
🔨 주요 변경 사항
- 기존 "/position/**"에서 각 HTTP 메소드에 따라 인가 범위 분리
✅ 리뷰 요청 사항
- 메소드와 엔드포인트 확인
⭐ 관련 이슈
#
=> refactor: position 엔드포인트 권한 수정

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveLineListDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/EmployeeLeaderDto.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml, momentum-dao-be/src/main/resources/mappers/approve/ApproveMapper.xml
closes #8 
---
📌 개요
프론트와의 연동을 위해 필드 추가
🔨 주요 변경 사항
- `ApproveLineListDTO` 에서 결재선 목록 아이디와 사원 아이디 추가
- `EmployeeLeaderDTO` 에서 leader의 부서 가져오기 (팀장이 결재 신청하는 경우엔 employee와 다르므로)
- `ApproveDetailMapper`, `ApproveMapper` 위에 DTO에서 추가한 필드들을 가져오기 위해 쿼리 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#8
=> feat : 프론트와의 기능 연동을 위한 필드 추가

momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/domain/aggregate/Kpi.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/command/application/service/KpiCommandServiceImplTest.java
closes #346
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> test : KPI 철회 테스트 코드 구현

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiDashboardRequestDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/response/KpiDashboardResponseDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/mapper/KpiQueryMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/evaluation/KpiQueryMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/controller/KpiQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/service/KpiQueryServiceImplTest.java
closes #354
---
📌 개요
🔨 주요 변경 사항
- 대시보드 KPI 조회 기능 구현
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> feat : 대시보드 KPI 조회 기능 구현

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/ReceiptFormStrategy.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveReceipt.java, momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveReceiptDTO.java, momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
closes #000
---
📌 개요
영수증 내역에서 필드명 수정
🔨 주요 변경 사항
- 영수증과 관련된 클래스에서 가게 주소 필드명 수정
`storeAddress` -> `address` 
✅ 리뷰 요청 사항
⭐ 관련 이슈
#8
=> refactor : 영수증 내역에서 필드명 수정

momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchDTO.java, momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchRequest.java, momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes #000
---
📌 개요
- 근태 전체 내역 필터 조건 추가
🔨 주요 변경 사항
- 정상 근무 여부 필터링 조건 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#12
=> refactor: 근태 전체 내역 조회 수정

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java
closes #8 
---
📌 개요
초과 근무에서 초과 근무 유형이 안보이는 문제 해결
🔨 주요 변경 사항
- 초과 근무에서 초과 근무 유형이 안보이는 문제 해결 : `ApproveServiceImpl`
✅ 리뷰 요청 사항
⭐ 관련 이슈
#8
=> 초과 근무에서 초과 근무 유형이 안보이는 문제 해결

momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/service/PositionCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/PositionRepository.java
📌 개요
- 직위 생성 및 수정 로직 변경
🔨 주요 변경 사항
- 직위 생성 및 수정 시 is_deleted 확인
✅ 리뷰 요청 사항
- 로직 확인
⭐ 관련 이슈
#
=> fix: 직위 생성 및 수정 로직 변경

momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveDTO.java, momentum-dao-be/src/main/resources/mappers/approve/ReceivedApproveMapper.xml
closes #6
---
📌 개요
받은 문서 조회 수정
🔨 주요 변경 사항
- 받은 문서 조회 시 결재를 해야 하는 문서 인지 참조를 해야 하는 문서 인지 구분되지 않음
- `receivedType` 필드를 생성해 구분함
✅ 리뷰 요청 사항
⭐ 관련 이슈
#6
=> fix : 받은 문서 조회 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DepartmentRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DeptHeadRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/infrastructure/repository/JpaDepHeadRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/infrastructure/repository/JpaDepartmentRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRolesRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/ManagerFinderService.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/interview/command/application/service/RetentionContactCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/calculator/RetentionScoreCalculatorImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/facade/RetentionForecastFacade.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/service/RetentionSupportCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/aggregate/StabilityType.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/controller/RetentionStatisticsQueryController.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/StabilityRatioByDeptRaw.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionAverageScoreDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionMonthlyStatDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionProgressDistributionDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/StabilityRatioByDeptDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/StabilityRatioSummaryDto.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/mapper/RetentionStatisticsMapper.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryService.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/retention/RetentionRoundMapper.xml, momentum-dao-be/src/main/resources/mappers/retention/RetentionStatisticsMapper.xml, momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/controller/RetentionStatisticsQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/controller/RetentionSupportQueryControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportQueryServiceImplTest.java
closes #000
---
📌 개요
🔨 주요 변경 사항
- 전체 안정성 비율 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : 근속 전망 통계 수정

momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
closes #000
---
📌 개요
- 근태 내역 조회 시 정렬 조건 기본값을 오름차순에서 내림차순으로 수정
🔨 주요 변경 사항
- xml 쿼리 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: 근태 내역 조회 쿼리 수정

momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationScoreServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/util/KpiPenaltyCalculator.java, momentum-dao-be/src/main/resources/mappers/retention/RetentionStatisticsMapper.xml
closes #000
---
📌 개요
🔨 주요 변경 사항
- KPI 감점 계산
- 통계 유형 조회
- 평가 기본 점수 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : KPI 감점 계산, 통계 유형 조회, 평가 기본 점수 수정

momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/response/HrEvaluationListResultDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/response/HrEvaluationWithFactorsDto.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/EvaluationHrServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiRequestQueryServiceImpl.java, momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationHrMapper.xml, momentum-dao-be/src/main/resources/mappers/evaluation/MyObjectionMapper.xml, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/controller/EvaluationHrControllerTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/EvaluationHrServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/command/application/service/RetentionInsightCommandServiceImplTest.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportQueryServiceImplTest.java
closes #000
---
📌 개요
🔨 주요 변경 사항
- KPI 취소 상태별 조회 문제 수정
- 인사 평가 조회 목록에 따른 요인별 점수 출력을 위한 출력 양식 수정
- 쿼리문 위치 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : KPI, HR 조회 문제 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
closes #000
---
📌 개요
🔨 주요 변경 사항
- SecurityConfig 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> init : SecurityConfig 수정

momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/dto/request/DepartmentUpdateRequest.java, momentum-dao-be/src/test/java/com/dao/momentum/organization/department/command/application/service/DepartmentCommandServiceTest.java
📌 개요
- 부서 관련 테스트코드 작성
🔨 주요 변경 사항
- 부서 수정 테스트코드 작성
- 부서 삭제 테스트코드 작성
✅ 리뷰 요청 사항
- 테스트케이스 로직 확인
⭐ 관련 이슈
#
=> test: 부서 관련 테스트코드 작성

momentum-dao-be/src/test/java/com/dao/momentum/organization/position/command/application/service/PositionCommandServiceTest.java
📌 개요
- 직위 테스트코드 수정
🔨 주요 변경 사항
- 직위 생성, 수정 시 유효성 검사 테스트코드 수정
✅ 리뷰 요청 사항
- 테스트코드 확인
⭐ 관련 이슈
#
=> test: 직위 테스트코드 수정

momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/Holiday.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/response/HolidayGetDTO.java, momentum-dao-be/src/test/java/com/dao/momentum/organization/company/command/application/service/HolidayCommandServiceTest.java, momentum-dao-be/src/test/java/com/dao/momentum/organization/company/query/service/HolidayQueryServiceTest.java
closes #000
---
📌 개요
- 휴일 관련 테스트코드 작성
🔨 주요 변경 사항
- 휴일 생성, 삭제, 조회 테스트코드 작성
✅ 리뷰 요청 사항
- 테스트코드 로직 확인
⭐ 관련 이슈
#
=> test: 휴일 관련 테스트코드 작성

momentum-dao-be/src/main/resources/mappers/evaluation/HrObjectionMapper.xml, momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportExcelMapper.xml
closes #000
---
📌 개요
🔨 주요 변경 사항
- 인사 평가 이의제기 요청 내역 조회 문제 수정
- 근속전망 엑셀 다운로드의 사위 부서 필터링 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : 인사 평가 이의제기 요청 내역 조회 문제 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractRetentionService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRolesRepository.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/interview/command/application/service/RetentionContactCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/calculator/RetentionScoreCalculatorImpl.java, momentum-dao-be/src/test/java/com/dao/momentum/retention/interview/command/application/service/RetentionContactCommandServiceImplTest.java
closes #000
---
📌 개요
🔨 주요 변경 사항
- 근속 전망 점수 확인을 위한 로그 추가
- 근속 전망 근속 점수 표기를 위한 로직 수정
- 면담 요청시 진행자의 팀장 권한 확인
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor : 근속 전망 로그 추가 및 로직 수정

momentum-dao-be/src/test/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImplTest.java
closes #000
---
📌 개요
테스트 에러 해결
🔨 주요 변경 사항
- 알림과 관련된 테스트 에러 해결 (매개변수 문제)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> teat : 테스트 에러 해결

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java, momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/repository/NotificationRepository.java, momentum-dao-be/src/test/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImplTest.java
closes #000
---
📌 개요
결재 문서 회수 관련 문제 해결
🔨 주요 변경 사항
- 결재 문서 회수 시 알림 내역도 삭제 되게 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#383
=> fix : 결재 문서 회수 관련 문제 해결

momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java, momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java, momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
📌 개요
- 비밀번호 재설정 관련 api 수정
🔨 주요 변경 사항
- 에러코드 추가
- resetToken 확인 엔트포인트 추가
✅ 리뷰 요청 사항
- 로직 확인
⭐ 관련 이슈
#
=> feat: 비밀번호 재설정 관련 api 수정

momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/CSVService.java
closes #000
---
📌 개요
- CSV 등록 에러 메시지 수정
🔨 주요 변경 사항
- 중복된 이메일 감지했을 때 몇 행인지 알려줄 수 있도록 수정
- 예시: 해당 이메일을 사용 중인 사원이 이미 존재합니다. -> [2행] 해당 이메일을 사용 중인 사원이 이미 존재합니다.
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: CSV 에러 메시지 수정

momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractCommandService.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/CSVService.java
closes #000
---
📌 개요
- 계약서 삭제 로직 수정 
- CSV 등록 로직 수정
🔨 주요 변경 사항
- S3 파일 삭제 로직 제거
- 사원 CSV 등록 시 비밀번호 초기 설정, 재설정 메일이 각각 발송되던 문제 수정 (후자 삭제)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> refactor: 계약서 삭제, CSV 등록 로직 수정

momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/VacationFormStrategy.java, momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/EmployeeRegisterRequest.java
📌 개요
- PR #418 배포 서버 반영
🔨 주요 변경 사항
- 잔여 휴가 일수/시간에 음수 들어오지 못하도록 어노테이션 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
=> 418번 PR 배포
